variables:
  GIT_SUBMODULE_STRATEGY: normal
  CI: "true"

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    - _site/vendor/
    - .bundled/
    - .yarn

stages:
  - build
  - test

build_job:
  stage: build
  before_script:
    - mkdir -p build
  script:
    - npm install
    - npm run build
  image: node:7.9.0-slim
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  tags:
    - docker

test_job:
  stage: test
  script:
    - npm test
  image: node:7.9.0-slim
  dependencies:
    - build_job
  tags:
    - docker
